-- Optional copy for a standalone Supabase project.
-- This Grok app uses Neon/PGLite via migrations/0002_pet_harmony.sql.

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  result_id text not null,
  product text not null check (product in ('tips', 'pdf')),
  paypal_order_id text not null unique,
  status text not null default 'created',
  created_at timestamptz not null default now()
);

create table if not exists public.results (
  result_id text primary key,
  payload jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.unlocks (
  id bigint generated by default as identity primary key,
  result_id text not null,
  product text not null check (product in ('tips', 'pdf')),
  paypal_order_id text not null unique,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  unique (result_id, product)
);
