/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCaptureRouteImport } from './routes/api/capture'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiOrdersRouteImport } from './routes/api/orders'
import { Route as ApiPaypalConfigRouteImport } from './routes/api/paypal-config'
import { Route as ApiReportLinkRouteImport } from './routes/api/report-link'
import { Route as ApiResultsRouteImport } from './routes/api/results'
import { Route as ApiUnlockStatusRouteImport } from './routes/api/unlock-status'
import { Route as ApiWebhookRouteImport } from './routes/api/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCaptureRoute = ApiCaptureRouteImport.update({
  id: '/api/capture',
  path: '/api/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaypalConfigRoute = ApiPaypalConfigRouteImport.update({
  id: '/api/paypal-config',
  path: '/api/paypal-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportLinkRoute = ApiReportLinkRouteImport.update({
  id: '/api/report-link',
  path: '/api/report-link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResultsRoute = ApiResultsRouteImport.update({
  id: '/api/results',
  path: '/api/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnlockStatusRoute = ApiUnlockStatusRouteImport.update({
  id: '/api/unlock-status',
  path: '/api/unlock-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookRoute = ApiWebhookRouteImport.update({
  id: '/api/webhook',
  path: '/api/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/capture': typeof ApiCaptureRoute
  '/api/health': typeof ApiHealthRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/paypal-config': typeof ApiPaypalConfigRoute
  '/api/report-link': typeof ApiReportLinkRoute
  '/api/results': typeof ApiResultsRoute
  '/api/unlock-status': typeof ApiUnlockStatusRoute
  '/api/webhook': typeof ApiWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/capture': typeof ApiCaptureRoute
  '/api/health': typeof ApiHealthRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/paypal-config': typeof ApiPaypalConfigRoute
  '/api/report-link': typeof ApiReportLinkRoute
  '/api/results': typeof ApiResultsRoute
  '/api/unlock-status': typeof ApiUnlockStatusRoute
  '/api/webhook': typeof ApiWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/capture': typeof ApiCaptureRoute
  '/api/health': typeof ApiHealthRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/paypal-config': typeof ApiPaypalConfigRoute
  '/api/report-link': typeof ApiReportLinkRoute
  '/api/results': typeof ApiResultsRoute
  '/api/unlock-status': typeof ApiUnlockStatusRoute
  '/api/webhook': typeof ApiWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/capture'
    | '/api/health'
    | '/api/orders'
    | '/api/paypal-config'
    | '/api/report-link'
    | '/api/results'
    | '/api/unlock-status'
    | '/api/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/capture'
    | '/api/health'
    | '/api/orders'
    | '/api/paypal-config'
    | '/api/report-link'
    | '/api/results'
    | '/api/unlock-status'
    | '/api/webhook'
  id:
    | '__root__'
    | '/'
    | '/api/capture'
    | '/api/health'
    | '/api/orders'
    | '/api/paypal-config'
    | '/api/report-link'
    | '/api/results'
    | '/api/unlock-status'
    | '/api/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCaptureRoute: typeof ApiCaptureRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiOrdersRoute: typeof ApiOrdersRoute
  ApiPaypalConfigRoute: typeof ApiPaypalConfigRoute
  ApiReportLinkRoute: typeof ApiReportLinkRoute
  ApiResultsRoute: typeof ApiResultsRoute
  ApiUnlockStatusRoute: typeof ApiUnlockStatusRoute
  ApiWebhookRoute: typeof ApiWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/capture': {
      id: '/api/capture'
      path: '/api/capture'
      fullPath: '/api/capture'
      preLoaderRoute: typeof ApiCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paypal-config': {
      id: '/api/paypal-config'
      path: '/api/paypal-config'
      fullPath: '/api/paypal-config'
      preLoaderRoute: typeof ApiPaypalConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/report-link': {
      id: '/api/report-link'
      path: '/api/report-link'
      fullPath: '/api/report-link'
      preLoaderRoute: typeof ApiReportLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/results': {
      id: '/api/results'
      path: '/api/results'
      fullPath: '/api/results'
      preLoaderRoute: typeof ApiResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unlock-status': {
      id: '/api/unlock-status'
      path: '/api/unlock-status'
      fullPath: '/api/unlock-status'
      preLoaderRoute: typeof ApiUnlockStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook': {
      id: '/api/webhook'
      path: '/api/webhook'
      fullPath: '/api/webhook'
      preLoaderRoute: typeof ApiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCaptureRoute: ApiCaptureRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiOrdersRoute: ApiOrdersRoute,
  ApiPaypalConfigRoute: ApiPaypalConfigRoute,
  ApiReportLinkRoute: ApiReportLinkRoute,
  ApiResultsRoute: ApiResultsRoute,
  ApiUnlockStatusRoute: ApiUnlockStatusRoute,
  ApiWebhookRoute: ApiWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
